version: "2.0"
services:
    #mysql:
    #  image: mysql
    #  environment:
    #    - MYSQL_ROOT_PASSWORD=gatherer1234
    #    - MYSQL_DATABASE=dbplayers
    gatherer1:
      image: graphicscore/xiv-gatherer:v0.4
    #  volumes:
    #    - ./target/XIVStats-Gatherer-Java-v1.4.0.jar:/usr/local/java/XIVStats-Gatherer-Java-v1.4.0-jar-with-dependencies.jar
    #  environment:
    #    - JAR_FILE=/usr/local/java/XIVStats-Gatherer-Java-v1.4.0-jar-with-dependencies.jar
      command: -g 1000000 -s 40350000 -f 50000000 -U mysql://localhost:3306 -u xivstats -p xivstats -d dbplayers -i -t 64
    #  links:
    #    - mysql
    #  depends_on:
    #    - mysql
    #gatherer2:
    #  image: bhits/java-jar-runner:8u102-jre
    #  volumes:
    #    - ./target/XIVStats-Gatherer-Java-v1.4.0.jar:/usr/local/java/XIVStats-Gatherer-Java-v1.4.0-jar-with-dependencies.jar
    #  environment:
    #    - JAR_FILE=/usr/local/java/XIVStats-Gatherer-Java-v1.4.0-jar-with-dependencies.jar
    #  command: -s 10001 -f 20000 -U mysql://mysql:3306 -u root -p gatherer1234 -d dbplayers -i -t 64
    #  links:
    #    - mysql
    #  depends_on:
    #    - mysql